### PR TITLE
add Text Components, change Modal styles

### PR DESCRIPTION
**Pull request by Winkel2019**

### CODE REVIEW

**Comment by olhanotolga** [comment]
@Winkel2019 

Thank you, Joyce!

I would ask you to move the `SingleBook` screen from the Saved Books stack. It is also accessible from Pool of Books (when you tap on the Swiper) and Matches, so it makes more sense to have `SingleBook` in the `screens/` folder.

Also, let's use the same-style icons everywhere. In our case, it's [Feather](https://icons.expo.fyi/) (this pack has everything we need + it's nicely rounded). Sorry about not emphasizing it in the beginning, I should create a style guideline on what we use and where/when — I wanted to have a finalized design first.

Otherwise, all good. Should I merge now or would you prefer to first make changes on this branch?

**Comment by Winkel2019** [comment]
ok, no worries. I will make changes, so leave it for now.

**Comment by olhanotolga** [comment]
Merging for now

**Comment by olhanotolga** [comment]
Whatever you did with that keyboard that disappears on click outside of the input area, it's awesome!!!

**Pull request merged**
